In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from IPython.display import clear_output

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/close-null-predected-new/close_null_predicted_new.csv
/kaggle/input/close-predicted/close_predicted.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/stock_list.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/sample_submission.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/options.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/financials.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/secondary_stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/trades.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/example_test_files/stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/jpx_tokyo_market_prediction/competition.cpython-37m-x86_64-linux-gnu.so
/kaggle/input/jpx-tokyo-stock-exchange-prediction/jpx_tokyo_market_prediction/__init__.py
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/stock_fin_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/trades_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/stock_price_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/options_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/data_specifications/stock_list_spec.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/options.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/financials.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/secondary_stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/trades.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/options.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/financials.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/secondary_stock_prices.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/trades.csv
/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/stock_prices.csv
/kaggle/input/close-null-predicted/close_null_predicted.csv

In [2]:
train_data = pd.read_csv('/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/stock_prices.csv')
train_length = len(train_data[(train_data['SecuritiesCode'] == 1301)])
Unique = np.unique(train_data['SecuritiesCode'].values)

In [3]:
df_preds = pd.read_csv('../input/close-predicted/close_predicted.csv')

In [4]:
del df_preds['Unnamed: 0']

In [5]:
Unique = np.unique(train_data['SecuritiesCode'].values)
Unique = list(Unique)
Unique = [int(i) for i in Unique]

In [6]:
for i in range(365):
    df_preds = df_preds.rename(columns={f'1{202+i}':f'{i+1}'})
df_preds

,1,2,3,4,5,6,7,8,9,10,...,356,357,358,359,360,361,362,363,364,365
0,2908.035342,2905.725237,2980.768597,2980.572117,2978.709132,2972.693527,2970.434507,2897.618241,2897.558353,2975.094674,...,3020.996958,3016.688043,2941.395079,2938.413651,3012.569753,3011.253385,3008.022212,3000.376212,2996.213230,2921.211408
1,525.123275,523.634010,571.746540,570.532430,568.874328,566.738092,564.390962,513.794596,511.976768,559.747324,...,498.081861,495.573539,444.965251,443.272296,491.288495,490.080376,488.522713,486.570984,484.479934,434.197066
2,1894.372302,1880.660562,2209.232041,2192.739614,2179.909108,2168.415431,2154.246581,1807.072410,1796.505731,2128.394875,...,1793.003326,1776.179291,1425.603232,1410.940540,1738.096250,1719.751654,1704.663776,1690.540889,1673.405978,1322.965005
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1232.826458,1227.817297,1341.805860,1336.811251,1330.396735,1327.152720,1320.994036,1198.318943,1193.530506,1307.772318,...,747.979252,741.497592,618.451386,613.248251,727.031803,721.827749,715.202360,711.745567,705.368492,582.462851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,505.020181,506.101589,549.635911,551.561172,552.739700,554.074640,554.243674,513.567878,514.622679,557.877567,...,335.746032,333.169981,290.103644,289.168801,330.869951,331.184268,331.006472,331.264692,330.653745,289.503798
1996,755.608831,754.834784,793.782727,792.924481,790.030856,787.989304,785.356983,746.174252,744.002589,781.529100,...,364.748604,362.992881,325.057180,324.468473,363.870094,363.721157,361.772597,360.885412,359.584502,321.873111
1997,1564.330904,1562.446313,1684.632531,1683.647851,1680.452915,1679.786757,1677.121372,1552.630505,1551.365049,1674.256378,...,1652.758936,1650.275920,1525.718908,1524.143947,1646.490609,1645.518161,1642.190131,1641.250206,1638.176651,1513.150935
1998,2264.268099,2259.475351,2370.122378,2366.870547,2358.563038,2347.601300,2347.127867,2229.522691,2224.927607,2336.217952,...,2455.489377,2458.350177,2343.600950,2341.302442,2454.256053,2453.064739,2446.514728,2436.953725,2437.475467,2320.417737
1999,653.535470,650.318787,677.785290,675.364903,671.661139,668.563781,666.441817,635.419716,633.760413,662.840297,...,-128.769105,-132.309374,-165.091855,-168.827840,-142.109908,-145.496399,-150.368103,-154.816086,-158.449304,-191.118938

In [7]:
df_preds = df_preds.reset_index(drop=True)
Unique_dict= {}
for i, unique in enumerate(Unique):
    Unique_dict[i] = unique
df_preds = df_preds.rename(index=Unique_dict)

In [8]:
df_null_index = pd.DataFrame([df_preds.isnull().sum(axis=1)])
df_null_index = df_null_index.transpose().rename(columns={0:'null_exist'})
df_null_exist = df_null_index[(df_null_index['null_exist'] != 0)]

In [9]:
null_list = [int(i) for i in list(df_null_exist.index)]
len(null_list)

135

In [10]:
df_preds_null = pd.read_csv('../input/close-null-predected-new/close_null_predicted_new.csv')

In [11]:
del df_preds_null['Unnamed: 0']

In [12]:
for i in range(365):
    df_preds_null = df_preds_null.rename(columns={f'1{202+i}':f'{i+1}'})
df_preds_null

,1,2,3,4,5,6,7,8,9,10,...,356,357,358,359,360,361,362,363,364,365
0,3727.201795,3723.060448,1243.130428,1239.070305,1234.440463,1230.345924,1225.384088,3700.062342,3696.547762,1217.253327,...,657.713172,652.401322,3126.754735,3122.936293,643.353737,639.662833,635.420077,631.725818,627.172317,3102.261666
1,10161.989375,10164.238153,2157.422824,2165.190785,2168.582474,2160.327337,2158.218947,10170.567566,10169.597422,2159.003318,...,1678.106775,1672.597384,9683.123111,9681.909343,1672.613241,1678.918804,1681.877283,1674.203222,1673.650323,9688.465394
2,7852.422546,7864.140444,1043.207269,1048.997136,1059.386531,1068.269775,1070.687594,7923.496866,7930.128954,1103.058694,...,931.144802,932.522802,7786.034730,7795.225621,972.659017,977.802266,988.613399,999.054530,1004.218513,7860.996974
3,1923.794211,1923.334970,563.508898,564.511687,562.725032,562.389128,562.465594,1922.653878,1922.843324,563.628573,...,517.073801,515.981257,1874.936496,1873.849583,513.336979,513.605799,511.050282,509.924022,509.202627,1868.599817
4,1884.105205,1885.475446,3313.315401,3307.456882,3309.746767,3312.762124,3313.801278,1898.679231,1900.800730,3328.745395,...,2290.882138,2285.796349,865.601339,863.801588,2289.045017,2281.253736,2282.345173,2284.945967,2286.382428,872.476028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,200.941557,200.284854,976.797847,976.982146,977.150695,974.024430,971.117599,193.150521,191.513698,967.124116,...,984.227190,982.735634,206.339303,206.388467,983.754448,984.918429,986.167978,984.194512,982.479543,205.708468
131,13517.059247,13525.217411,3009.367304,3016.065119,3021.672714,3032.384808,3049.344470,13570.595064,13577.325718,3059.881740,...,4088.177494,4105.619733,14627.748084,14635.752339,4119.972548,4126.973410,4133.122233,4144.615583,4162.594318,14685.095173
132,4015.005431,4013.904186,1557.725090,1556.357504,1555.021952,1554.446538,1552.246641,4005.608147,4004.252064,1548.050002,...,1820.618261,1820.501195,4275.771598,4276.095623,1821.294038,1821.217869,1821.050389,1821.484548,1820.103636,4274.065405
133,8297.950322,8301.008400,1365.490036,1368.787553,1370.712666,1367.552538,1374.079038,8316.639195,8318.340719,1381.131825,...,954.301694,961.279614,7904.595654,7907.425328,971.779264,975.101635,977.254968,974.574204,981.874112,7925.538071
134,20203.351956,20202.184787,5352.987622,5359.248973,5352.126459,5348.774980,5363.654352,20205.895900,20209.775211,5366.689177,...,7194.259456,7205.540578,22042.392263,22038.971523,7186.589679,7188.625912,7176.145363,7166.230324,7173.290450,22006.431360

In [13]:
for i,unique in enumerate(null_list):

    df_preds_null = df_preds_null.rename(index={i:unique})

In [14]:
df_preds = df_preds.drop(null_list)

In [15]:
df_all = pd.concat((df_preds, df_preds_null), axis=0).sort_index()
df_all

,1,2,3,4,5,6,7,8,9,10,...,356,357,358,359,360,361,362,363,364,365
1301,2908.035342,2905.725237,2980.768597,2980.572117,2978.709132,2972.693527,2970.434507,2897.618241,2897.558353,2975.094674,...,3020.996958,3016.688043,2941.395079,2938.413651,3012.569753,3011.253385,3008.022212,3000.376212,2996.213230,2921.211408
1332,525.123275,523.634010,571.746540,570.532430,568.874328,566.738092,564.390962,513.794596,511.976768,559.747324,...,498.081861,495.573539,444.965251,443.272296,491.288495,490.080376,488.522713,486.570984,484.479934,434.197066
1333,1894.372302,1880.660562,2209.232041,2192.739614,2179.909108,2168.415431,2154.246581,1807.072410,1796.505731,2128.394875,...,1793.003326,1776.179291,1425.603232,1410.940540,1738.096250,1719.751654,1704.663776,1690.540889,1673.405978,1322.965005
1375,3727.201795,3723.060448,1243.130428,1239.070305,1234.440463,1230.345924,1225.384088,3700.062342,3696.547762,1217.253327,...,657.713172,652.401322,3126.754735,3122.936293,643.353737,639.662833,635.420077,631.725818,627.172317,3102.261666
1376,1232.826458,1227.817297,1341.805860,1336.811251,1330.396735,1327.152720,1320.994036,1198.318943,1193.530506,1307.772318,...,747.979252,741.497592,618.451386,613.248251,727.031803,721.827749,715.202360,711.745567,705.368492,582.462851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,505.020181,506.101589,549.635911,551.561172,552.739700,554.074640,554.243674,513.567878,514.622679,557.877567,...,335.746032,333.169981,290.103644,289.168801,330.869951,331.184268,331.006472,331.264692,330.653745,289.503798
9991,755.608831,754.834784,793.782727,792.924481,790.030856,787.989304,785.356983,746.174252,744.002589,781.529100,...,364.748604,362.992881,325.057180,324.468473,363.870094,363.721157,361.772597,360.885412,359.584502,321.873111
9993,1564.330904,1562.446313,1684.632531,1683.647851,1680.452915,1679.786757,1677.121372,1552.630505,1551.365049,1674.256378,...,1652.758936,1650.275920,1525.718908,1524.143947,1646.490609,1645.518161,1642.190131,1641.250206,1638.176651,1513.150935
9994,2264.268099,2259.475351,2370.122378,2366.870547,2358.563038,2347.601300,2347.127867,2229.522691,2224.927607,2336.217952,...,2455.489377,2458.350177,2343.600950,2341.302442,2454.256053,2453.064739,2446.514728,2436.953725,2437.475467,2320.417737
9997,653.535470,650.318787,677.785290,675.364903,671.661139,668.563781,666.441817,635.419716,633.760413,662.840297,...,-128.769105,-132.309374,-165.091855,-168.827840,-142.109908,-145.496399,-150.368103,-154.816086,-158.449304,-191.118938

In [16]:
for code in df_all.index:
    for i in range(363):
        i = i+1
        df_all.loc[code,f'{i}'] = (df_all.loc[code,f'{i + 2}'] - df_all.loc[code,f'{i + 1}']) / df_all.loc[code,f'{i + 1}']

df_all

,1,2,3,4,5,6,7,8,9,10,...,356,357,358,359,360,361,362,363,364,365
1301,0.025826,-0.000066,-0.000625,-0.002020,-0.000760,-0.024514,-0.000021,0.026759,0.000851,0.000365,...,-0.024959,-0.001014,0.025237,-0.000437,-0.001073,-0.002542,-0.001387,-0.025032,2996.213230,2921.211408
1332,0.091882,-0.002124,-0.002906,-0.003755,-0.004141,-0.089648,-0.003538,0.093306,-0.002779,-0.003557,...,-0.102121,-0.003805,0.108322,-0.002459,-0.003178,-0.003995,-0.004298,-0.103787,484.479934,434.197066
1333,0.174711,-0.007465,-0.005851,-0.005273,-0.006534,-0.161158,-0.005847,0.184741,-0.006124,-0.004378,...,-0.197377,-0.010285,0.231871,-0.010554,-0.008773,-0.008285,-0.010136,-0.209418,1673.405978,1322.965005
1375,-0.666100,-0.003266,-0.003737,-0.003317,-0.004033,2.019512,-0.000950,-0.670705,-0.002804,-0.003269,...,3.792686,-0.001221,-0.793991,-0.005737,-0.006633,-0.005814,-0.007208,3.946426,627.172317,3102.261666
1376,0.092838,-0.003722,-0.004798,-0.002438,-0.004641,-0.092866,-0.003996,0.095718,-0.003593,-0.004654,...,-0.165943,-0.008413,0.185542,-0.007158,-0.009179,-0.004833,-0.008960,-0.174243,705.368492,582.462851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,0.086019,0.003503,0.002137,0.002415,0.000305,-0.073390,0.002054,0.084052,0.002526,0.000799,...,-0.129262,-0.003222,0.144210,0.000950,-0.000537,0.000780,-0.001844,-0.124450,330.653745,289.503798
9991,0.051598,-0.001081,-0.003649,-0.002584,-0.003341,-0.049892,-0.002910,0.050439,-0.002897,-0.005449,...,-0.104508,-0.001811,0.121434,-0.000409,-0.005357,-0.002452,-0.003605,-0.104875,359.584502,321.873111
9993,0.078202,-0.000585,-0.001898,-0.000396,-0.001587,-0.074229,-0.000815,0.079215,-0.000122,-0.001403,...,-0.075476,-0.001032,0.080272,-0.000591,-0.002022,-0.000572,-0.001873,-0.076320,1638.176651,1513.150935
9994,0.048970,-0.001372,-0.003510,-0.004648,-0.000202,-0.050106,-0.002061,0.050020,-0.000923,-0.002899,...,-0.046677,-0.000981,0.048244,-0.000485,-0.002670,-0.003908,0.000214,-0.048024,2437.475467,2320.417737
9997,0.042235,-0.003571,-0.005484,-0.004611,-0.003174,-0.046549,-0.002611,0.045885,-0.001169,-0.003095,...,0.247771,0.022630,-0.158255,0.023830,0.033483,0.029581,0.023468,0.206184,-158.449304,-191.118938

In [17]:
del df_all['364']
del df_all['365']

In [18]:
df_all = df_all.rank(method='first',ascending=False).astype(int) -1

In [19]:
df_all.reset_index(inplace=True)

In [20]:
import jpx_tokyo_market_prediction
env = jpx_tokyo_market_prediction.make_env()   # initialize the environment
iter_test = env.iter_test()    # an iterator which loops over the test files
i = '1'
for (prices, options, financials, trades, secondary_prices, sample_prediction) in iter_test:
    del sample_prediction['Rank']
    sample_prediction['Rank'] = df_all[[i]]
    i = str(int(i) + 1)
    print(sample_prediction)
    env.predict(sample_prediction)

This version of the API is not optimized and should not be used to estimate the runtime of your code on the hidden test set.
            Date  SecuritiesCode  Rank
0     2021-12-06            1301  1570
1     2021-12-06            1332   953
2     2021-12-06            1333   461
3     2021-12-06            1375  1876
4     2021-12-06            1376   946
...          ...             ...   ...
1995  2021-12-06            9990   997
1996  2021-12-06            9991  1363
1997  2021-12-06            9993  1090
1998  2021-12-06            9994  1390
1999  2021-12-06            9997  1439

[2000 rows x 3 columns]
            Date  SecuritiesCode  Rank
0     2021-12-07            1301   712
1     2021-12-07            1332  1261
2     2021-12-07            1333  1863
3     2021-12-07            1375  1503
4     2021-12-07            1376  1583
...          ...             ...   ...
1995  2021-12-07            9990   166
1996  2021-12-07            9991  1002
1997  2021-12-07            9993   854
1998  2021-12-07            9994  1076
1999  2021-12-07            9997  1558

[2000 rows x 3 columns]